sudo: required
services:
- docker
script:
- chmod +x travis_script.sh
- ./travis_script.sh

# http://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
branches:
  only:
    - master
