sudo: required
services:
- docker

language: go
go:
  - 1.7

script:
  - "./docker/docker_run.sh" # run tests in docker
  - "env SKIP_TESTS=1 ./buildRelease.sh"
  - "./releaseLatest.sh"

env:
  global:
    secure: Q+Pp6hV1h7XJ6kWarbIuVtbsytfM5yh20duTKhsE6tltIbUpaXuJ91wz2j1PPWuUZxRu7+y+SGpRz0NbH9vAkBOiZcKmqjowe/W0qOx52wVFYhr1HULi0SqJO7TZTjlfWz/6h/I81fn/+ZZ5Dfnb4rlK/nsExOnF2aShGg3EuxI=
