sudo: required
services:
- docker
language: go
go:
- 1.7
script:
- chmod +x travis_script.sh
- ./travis_script.sh

env:
  global:
    secure: LIEPF0q0NpT6dhaswPr33u8DY01Dm3Qzr4g0MuDPPYOoL0hI1O5DhPugwk0DPOJbqieXuA5mKcqv1T3vg6TUjqr5G/U7B8p7UmRf4e1HjrDqePpWNvG0i/AF++/akwjpDCa5kWXhqxB+gPYEL3jl+jz8aALrnuK0MULJ/4ZD48I=

# http://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
branches:
  only:
    - master
